### ISSUE TITLE
1.0 roadmap

### ISSUE THREAD

**Issue by sstok** [rollerworks/datagrid#41]
#1.0 will not be released anytime soon, but here is a list of things I would like to work on.

The biggest change is immutability of the datagrid configuration and inter dependency of objects.
And improving DX while keeping performance high.

## 0.8.0

- [x] Auto configure a "label" for column (when non was set), humanize column-name.
- [x] Views should not be aware of the Datagrid and it's Columns, this reduces memory usage and makes it possible to cache the rendered view.
- [x] Make Datagrid object immutable, use the builder to build a new Datagrid;
    - [x] Setting data is only possible once! Data cannot be changed afterwards;
 - [x] Require that Data is in the correct format (Traversable) before setting it in the Datagrid.
   So no more event listeners like pre/post set-data
